import PDFDocument from "pdfkit";
function money(amount, currency) {
  try {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: currency || "USD",
    }).format(amount);
  } catch {
    return `${(amount ?? 0).toFixed(2)} ${currency || ""}`.trim();
  }
}
function formatDate(date) {
  return new Date(date).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}
const PAGE_MARGIN = 50;
const COLORS = {
  heading: "#111827",
  body: "#374151",
  muted: "#6b7280",
  rule: "#e5e7eb",
  brand: "#3b5fd9",
};
function rule(doc) {
  doc
    .strokeColor(COLORS.rule)
    .lineWidth(1)
    .moveTo(PAGE_MARGIN, doc.y)
    .lineTo(doc.page.width - PAGE_MARGIN, doc.y)
    .stroke();
}
export function generatePaymentRequestPdf(
  res,
  { requester, participant, description, expenseDate, totalAmount, currency },
) {
  const doc = new PDFDocument({
    margin: PAGE_MARGIN,
    size: "A4",
  });
  doc.pipe(res);
  doc
    .fillColor(COLORS.brand)
    .fontSize(22)
    .font("Helvetica-Bold")
    .text("Payment Request");
  doc.moveDown(0.3);
  doc
    .fillColor(COLORS.muted)
    .fontSize(10)
    .font("Helvetica")
    .text(`From ${requester.name} · ${requester.email}`);
  doc.text(`Date issued: ${formatDate(new Date())}`);
  doc.moveDown(1.25);
  rule(doc);
  doc.moveDown(1);
  doc.fillColor(COLORS.muted).fontSize(10).font("Helvetica").text("Billed to");
  doc
    .fillColor(COLORS.heading)
    .fontSize(15)
    .font("Helvetica-Bold")
    .text(participant.name);
  if (participant.email) {
    doc
      .fillColor(COLORS.muted)
      .fontSize(10)
      .font("Helvetica")
      .text(participant.email);
  }
  doc.moveDown(1.25);
  doc.fillColor(COLORS.muted).fontSize(10).font("Helvetica").text("For");
  doc
    .fillColor(COLORS.body)
    .fontSize(12)
    .font("Helvetica")
    .text(description || "Shared expense");
  doc
    .fillColor(COLORS.muted)
    .fontSize(10)
    .font("Helvetica")
    .text(`Original expense date: ${formatDate(expenseDate)}`);
  doc.text(`Total expense: ${money(totalAmount, currency)}`);
  doc.moveDown(1.25);
  rule(doc);
  doc.moveDown(1);
  doc.fillColor(COLORS.muted).fontSize(11).font("Helvetica").text("Amount due");
  doc
    .fillColor(COLORS.brand)
    .fontSize(30)
    .font("Helvetica-Bold")
    .text(money(participant.shareAmount, currency));
  doc.moveDown(2);
  doc
    .fillColor(COLORS.muted)
    .fontSize(9)
    .font("Helvetica")
    .text(
      "This is an informal reminder generated by FinTrack, not an invoice or a legal demand for payment.",
      {
        width: doc.page.width - PAGE_MARGIN * 2,
      },
    );
  doc.end();
}
